# Generated by Django 4.1.2 on 2022-10-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name_employee',
        ),
    ]
