# Generated by Django 4.1.2 on 2022-10-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
