# Generated by Django 4.1.2 on 2022-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
